baseURL: "https://sebastiantillbraun.com"
title: Sebastian Till Braun
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
       # - name: Books
       #   url: books/
       #   weight: 5 
        - name: About
          url: about/
          weight: 1
        - name: News
          url: /news/
          weight: 2
        - name: Papers
          url: papers/
          weight: 3
        #- name: In Progress
        #  url: progress/
        #  weight: 4
        - name: Data
          url: data/
          weight: 5
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: "This website hosts Sebastian Braun's CV, research papers, data, and contact information"
    author: Sebastian Till Braun
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","data", "about"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sebastian Till Braun
          subtitle: "Fielmann Professor for Economics of Global Transformation at [Kiel Institute](https://www.kielinstitut.de/) and [Kiel University](https://www.uni-kiel.de/en/)"
          imageUrl: "pictureneu.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: News
              url: news/
            #- name: In Progress
            #   url: progress/
            - name: Papers
              url: papers/
            #- name: Tags
             # url: tags/
            - name: Data
              url: data/
            #- name: Archive
            #  url: archive/


    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:sebastian.braun@kielinstitut.de
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: https://calendly.com/sebastian-braun/officehours
        - name: Google Scholar
          url: https://scholar.google.de/citations?user=ko1Ng4EAAAAJ
        - name: Twitter
          url: https://x.com/SebastianTBraun
        - name: Bluesky
          url: https://bsky.app/profile/sebastiantbraun.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Sebastian Till Braun"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2